In [1]:
import pandas as pd

df = pd.read_csv('data/raw/data.csv')
df

,municipio,propriedade,ponto,data_hora,periodo,ACI_TOTAL_D,ACI_BYMIN_D,ACI_j60_total_D,ACI_j60_bymin_D,NDSI_D,...,green_cover_100m,green_cover_1000m,NDVI_mean_100m,NDVI_mean_1000m,NDVI_sd_100m,NDVI_sd_1000m,NDVI_min_100m,NDVI_min_1000m,NDVI_max_100m,NDVI_max_1000m
0,Mossoró,HARAS FVF,1,2024-08-31 12:00:00,tarde,11741.939447,3913.98,1012.583201,337.53,0.706134,...,0.0,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362
1,Mossoró,HARAS FVF,1,2024-08-31 12:10:00,tarde,10519.522031,3506.51,858.023149,286.01,0.998002,...,0.0,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362
2,Mossoró,HARAS FVF,1,2024-08-31 12:20:00,tarde,11271.444914,3757.15,940.105685,313.37,0.979536,...,0.0,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362
3,Mossoró,HARAS FVF,1,2024-08-31 12:30:00,tarde,11196.194115,3732.06,906.124303,302.04,0.995438,...,0.0,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362
4,Mossoró,HARAS FVF,1,2024-08-31 12:40:00,tarde,12191.727545,4063.91,1058.017725,352.67,0.621718,...,0.0,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137512,Mossoró,UFERSA,40,2025-01-01 18:10:00,noite,12096.640919,4034.48,694.960478,231.78,0.495447,...,0.0,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336
137513,Mossoró,UFERSA,40,2025-01-01 18:20:00,noite,12018.555368,4008.44,690.859558,230.42,0.491442,...,0.0,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336
137514,Mossoró,UFERSA,40,2025-01-01 18:30:00,noite,11982.657296,3996.47,688.423305,229.60,0.491222,...,0.0,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336
137515,Mossoró,UFERSA,40,2025-01-01 18:40:00,noite,11942.358673,3983.03,686.648749,229.01,0.487092,...,0.0,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336
137516,Mossoró,UFERSA,40,2025-01-01 18:50:00,noite,7901.352308,3954.02,347.506591,173.90,0.494173,...,0.0,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336

In [7]:
df['ponto_periodo'] = df['ponto'].astype(str) + '_' + df['periodo'].astype(str)
df

,municipio,propriedade,ponto,data_hora,periodo,ACI_TOTAL_D,ACI_BYMIN_D,ACI_j60_total_D,ACI_j60_bymin_D,NDSI_D,...,green_cover_1000m,NDVI_mean_100m,NDVI_mean_1000m,NDVI_sd_100m,NDVI_sd_1000m,NDVI_min_100m,NDVI_min_1000m,NDVI_max_100m,NDVI_max_1000m,ponto_periodo
0,Mossoró,HARAS FVF,1,2024-08-31 12:00:00,tarde,11741.939447,3913.98,1012.583201,337.53,0.706134,...,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362,1_tarde
1,Mossoró,HARAS FVF,1,2024-08-31 12:10:00,tarde,10519.522031,3506.51,858.023149,286.01,0.998002,...,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362,1_tarde
2,Mossoró,HARAS FVF,1,2024-08-31 12:20:00,tarde,11271.444914,3757.15,940.105685,313.37,0.979536,...,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362,1_tarde
3,Mossoró,HARAS FVF,1,2024-08-31 12:30:00,tarde,11196.194115,3732.06,906.124303,302.04,0.995438,...,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362,1_tarde
4,Mossoró,HARAS FVF,1,2024-08-31 12:40:00,tarde,12191.727545,4063.91,1058.017725,352.67,0.621718,...,1.630070,0.155014,0.166381,0.018346,0.032351,0.102713,-0.032152,0.229028,0.439362,1_tarde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137512,Mossoró,UFERSA,40,2025-01-01 18:10:00,noite,12096.640919,4034.48,694.960478,231.78,0.495447,...,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336,40_noite
137513,Mossoró,UFERSA,40,2025-01-01 18:20:00,noite,12018.555368,4008.44,690.859558,230.42,0.491442,...,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336,40_noite
137514,Mossoró,UFERSA,40,2025-01-01 18:30:00,noite,11982.657296,3996.47,688.423305,229.60,0.491222,...,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336,40_noite
137515,Mossoró,UFERSA,40,2025-01-01 18:40:00,noite,11942.358673,3983.03,686.648749,229.01,0.487092,...,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336,40_noite
137516,Mossoró,UFERSA,40,2025-01-01 18:50:00,noite,7901.352308,3954.02,347.506591,173.90,0.494173,...,1.403094,0.155712,0.151985,0.012076,0.036346,0.117919,-0.027587,0.186500,0.463336,40_noite

In [8]:
df.to_csv('data/raw/data_v2.csv', index=False)

In [9]:
df['ponto_periodo'].nunique()

141